# Three-Address Code (TAC) - Unoptimized
# Generated by Minimal C Compiler
# ─────────────────────────────────────

 1: DECL x
 2: DECL y
 3: DECL z
 4: x = 10
 5: y = 20
 6: t0 = x + y
 7: z = t0
 8: PRINT z
 9: t1 = z + 5
10: x = t1
11: PRINT x
12: t2 = x + y
13: t3 = t2 + z
14: y = t3
15: PRINT y
