# Three-Address Code (TAC) - Optimized
# Generated by Minimal C Compiler
# Optimizations applied: Constant folding, Copy propagation
# ─────────────────────────────────────

 1: DECL x
 2: DECL y
 3: DECL z
 4: x = 10
 5: y = 20
 6: t0 = 30
 7: z = 30
 8: PRINT 30
 9: t1 = 35
10: x = 35
11: PRINT 35
12: t2 = 55
13: t3 = 85
14: y = 85
15: PRINT 85
